name: Run Python Script

on: 
  workflow_dispatch:

env:
  subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  tenant_id: ${{ secrets.TENANT_ID }}
  rg-videos-name: ${{ secrets.RESOURCE_GROUP_NAME }}
  synapse_videos_workspace_name: ${{ secrets.SYNAPSE_WORKSPACE_NAME }}
  sp-videos-client-id: ${{ secrets.SP_VIDEOS_CLIENT_ID }}
  sp-videos-client-secret: ${{ secrets.SP_VIDEOS_CLIENT_SECRET }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Python Script
        run: |
          python -m pip install requests
          python mypythonscript.py

  run-python-via-powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            python -m pip install requests
            python GitHub-Actions-Python\mypythonscriptPS.py


